### ISSUE TITLE
Stuffed beneath the obsidian when tp back to overworld

### ISSUE THREAD

**Issue by LTCatt** [YUNG-GANG/YUNGs-Better-Portals#30] opened 2021-05-27 02:47 UTC
If the cave is filled with water, this will cause the Dimensional Plasma in the top layer to be converted directly to obsidian.
Then when I return to overworld from the nether, I'm teleported into the Dimensional Plasma below the obsidian layer...

**Comment by yungnickyoung** [comment] 2021-06-01 18:02
Duplicate of #17

**Closed as completed by yungnickyoung** 2021-06-01 18:02 UTC
