### ISSUE TITLE
Crash while teleporting player

### ISSUE THREAD

**Issue by RustBandit** [YUNG-GANG/YUNGs-Better-Portals#18] opened 2021-03-12 07:46 UTC
I have a number of mods in I won't lie, but when I added terraforged I started to get crashes, so i loaded up a world not using terraforged and its still broken, help?
[crash-2021-03-12_02.32.52-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/6128346/crash-2021-03-12_02.32.52-server.txt)

**Comment by yungnickyoung** [comment] 2021-04-18 06:40
Potential duplicate of #19 . You still have Terraforged loaded in this crash report.

**Comment by yungnickyoung** [comment] 2021-07-16 22:05
It seems this is a null pointer crash when trying to find the target dimension to teleport to. My guess is that you changed your rift variant settings after initially generating some dimensional rifts. Meaning you tried to teleport in a rift placed in a dimension that no longer had any settings associated with it. Either that, or adding Terraforged somehow caused a problem, although I doubt this since Terraforged wouldn't be altering any dimension IDs.

Either way, I'll be putting a null pointer check in an upcoming release so that the crash won't happen.

**Comment by yungnickyoung** [comment] 2021-07-16 22:32
Should be fixed in v0.3.5. Please open a new issue if the problem continues!

**Closed as completed by yungnickyoung** 2021-07-16 22:32 UTC
Labels: bug
