### ISSUE TITLE
[BUG] Random crash, not sure what causing that.

### ISSUE THREAD

**Issue by KKotik** [YUNG-GANG/YUNGs-Better-Portals#35] opened 2021-06-22 16:10 UTC
[crash-2021-06-22_19.05.09-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Portals/files/6695843/crash-2021-06-22_19.05.09-server.txt)

**Comment by yungnickyoung** [comment] 2021-06-22 16:19
Duplicate of #21

**Closed as completed by yungnickyoung** 2021-06-22 16:19 UTC
Labels: duplicate
